#TODO: Complete this 
version: '3.6'
services:
  db:
    image: mysql:8
    ports:
      - '3306:3306' # expose pg on port 5932 to not collide with pg from elsewhere
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}

volumes:
  db_data:
