#TODO: Complete this 
version: '3.6'
name: "database"
services:
  db:
    image: mysql:8
    ports:
      - '3306:3306' #
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}

volumes:
  db:
    driver: local
